apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: first
  name: first-dep
spec:
  selector:
    matchLabels:
      app: first-dep
  template:
    metadata:
      labels:
        app: first-dep
    spec:
      containers:
      - name: first-dep-nginx
        image: nginx:latest
        ports:
        - containerPort: 80

      - name: first-dep-tomcat
        image: tomcat:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  namespace: first
  name: first-service
spec:
  selector:
    app: firs-dep
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer