apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-dep
spec:
  selector:
    matchLabels:
      app: first-dep
  template:
    metadata:
      labels:
        app: first-dep
    spec:
      containers:
      - name: first-dep-nginx
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

      - name: first-dep-tomcat
        image: tomcat:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: first-service
spec:
  selector:
    app: firs-dep
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer